# Generated by Django 4.2.2 on 2024-02-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0457_backfill_scheduledmessagenotificationemail_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmuserdefault",
            name="default_language",
            field=models.CharField(default="zh-cn", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="default_language",
            field=models.CharField(default="zh-cn", max_length=50),
        ),
    ]
