# Generated by Django 4.2.2 on 2024-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0458_alter_realmuserdefault_default_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="default_language",
            field=models.CharField(default="zh-cn", max_length=50),
        ),
    ]
